"""
Seed script: 30 соискателей для базы кадрового агентства.
Запуск: python seed_candidates.py  (внутри контейнера backend)
"""

import asyncio
import os

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.models.candidate import Candidate

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://crm_user:crm_pass@postgres:5432/crm_db",
)

CANDIDATES = [
    # --- Няни ---
    {
        "full_name": "Иванова Светлана Юрьевна",
        "age": 38,
        "specialization": "няня",
        "experience_years": 8,
        "salary_min": 60000,
        "salary_max": 75000,
        "availability": "с 1 мая 2026",
        "contacts": {"telegram": "@svetlana_nanny", "whatsapp": "+79161234501"},
        "tags": ["дети до 3 лет", "грудной уход", "английский язык", "проживание"],
        "notes": "Медицинское образование. Опыт с новорождёнными. Рекомендации от 3 семей.",
    },
    {
        "full_name": "Петрова Наталья Александровна",
        "age": 44,
        "specialization": "няня",
        "experience_years": 12,
        "salary_min": 70000,
        "salary_max": 90000,
        "availability": "сразу",
        "contacts": {"telegram": "@natasha_babysit", "email": "petrova.nat@mail.ru"},
        "tags": ["дети 3-10 лет", "школьная программа", "развивающие занятия", "выезд за рубеж"],
        "notes": "Педагогическое образование, МГПУ. Готова к командировкам с семьёй.",
    },
    {
        "full_name": "Смирнова Ольга Витальевна",
        "age": 32,
        "specialization": "няня / гувернантка",
        "experience_years": 5,
        "salary_min": 80000,
        "salary_max": 110000,
        "availability": "с 15 мая 2026",
        "contacts": {"whatsapp": "+79031234502", "email": "smirnova.olga@gmail.com"},
        "tags": ["английский C1", "французский B2", "дети 4-14 лет", "помощь с уроками"],
        "notes": "Дипломированный педагог и переводчик. Работала в семьях топ-менеджеров.",
    },
    {
        "full_name": "Захарова Марина Дмитриевна",
        "age": 29,
        "specialization": "няня",
        "experience_years": 3,
        "salary_min": 50000,
        "salary_max": 65000,
        "availability": "сразу",
        "contacts": {"telegram": "@marina_zah"},
        "tags": ["дети до 5 лет", "творческие занятия", "прогулки"],
        "notes": "Молодая активная няня, психолог по образованию.",
    },
    {
        "full_name": "Козлова Тамара Ивановна",
        "age": 52,
        "specialization": "няня / помощница по хозяйству",
        "experience_years": 18,
        "salary_min": 55000,
        "salary_max": 70000,
        "availability": "с 1 июня 2026",
        "contacts": {"whatsapp": "+79211234503"},
        "tags": ["дети любого возраста", "уборка", "приготовление еды", "проживание"],
        "notes": "Многолетний опыт, отличные рекомендации. Готова к проживанию в доме.",
    },
    # --- Повара ---
    {
        "full_name": "Морозов Андрей Сергеевич",
        "age": 41,
        "specialization": "повар / шеф-повар",
        "experience_years": 15,
        "salary_min": 100000,
        "salary_max": 140000,
        "availability": "с 1 мая 2026",
        "contacts": {"telegram": "@chef_morozov", "whatsapp": "+79261234504"},
        "tags": ["европейская кухня", "русская кухня", "здоровое питание", "банкеты"],
        "notes": "Работал личным поваром в семьях Москвы. Знает диетические ограничения.",
    },
    {
        "full_name": "Лебедева Анна Павловна",
        "age": 35,
        "specialization": "повар / кондитер",
        "experience_years": 10,
        "salary_min": 70000,
        "salary_max": 95000,
        "availability": "сразу",
        "contacts": {"telegram": "@anna_confectioner", "email": "lebed.anna@yandex.ru"},
        "tags": ["выпечка", "торты на заказ", "итальянская кухня", "детское питание"],
        "notes": "Специализируется на безглютеновой и вегетарианской кухне.",
    },
    {
        "full_name": "Новиков Павел Олегович",
        "age": 27,
        "specialization": "повар",
        "experience_years": 4,
        "salary_min": 55000,
        "salary_max": 75000,
        "availability": "сразу",
        "contacts": {"whatsapp": "+79151234505"},
        "tags": ["азиатская кухня", "суши", "быстрое приготовление", "meal prep"],
        "notes": "Специализируется на азиатской кухне и здоровом питании.",
    },
    # --- Горничные / Уборщицы ---
    {
        "full_name": "Фёдорова Галина Николаевна",
        "age": 45,
        "specialization": "горничная / экономка",
        "experience_years": 14,
        "salary_min": 60000,
        "salary_max": 80000,
        "availability": "с 10 мая 2026",
        "contacts": {"telegram": "@galina_clean", "whatsapp": "+79091234506"},
        "tags": ["генеральная уборка", "стирка", "глажка", "уход за одеждой", "управление хозяйством"],
        "notes": "Работала в загородных домах. Умеет управлять персоналом.",
    },
    {
        "full_name": "Волкова Елена Геннадьевна",
        "age": 39,
        "specialization": "горничная",
        "experience_years": 7,
        "salary_min": 50000,
        "salary_max": 65000,
        "availability": "сразу",
        "contacts": {"whatsapp": "+79181234507"},
        "tags": ["уборка квартир", "уход за домом", "деликатные поверхности", "цветы"],
        "notes": "Аккуратная, ответственная. Умеет работать с дорогими поверхностями и антиквариатом.",
    },
    {
        "full_name": "Соловьёва Ирина Михайловна",
        "age": 33,
        "specialization": "горничная / помощница по хозяйству",
        "experience_years": 5,
        "salary_min": 45000,
        "salary_max": 60000,
        "availability": "с 20 мая 2026",
        "contacts": {"telegram": "@irina_help"},
        "tags": ["уборка", "закупки", "приготовление несложных блюд"],
        "notes": "Исполнительная, пунктуальная. Водительские права категории B.",
    },
    # --- Гувернантки ---
    {
        "full_name": "Белова Екатерина Владимировна",
        "age": 36,
        "specialization": "гувернантка",
        "experience_years": 9,
        "salary_min": 90000,
        "salary_max": 130000,
        "availability": "с 1 июня 2026",
        "contacts": {"telegram": "@katya_gov", "email": "belova.ekaterina@gmail.com"},
        "tags": ["английский C2", "немецкий B2", "дети 5-16 лет", "подготовка к ЕГЭ", "выезд за рубеж"],
        "notes": "Кандидат педагогических наук. Готова к переезду с семьёй.",
    },
    {
        "full_name": "Тихонова Юлия Романовна",
        "age": 28,
        "specialization": "гувернантка / репетитор",
        "experience_years": 4,
        "salary_min": 75000,
        "salary_max": 100000,
        "availability": "сразу",
        "contacts": {"telegram": "@yulia_tutor", "whatsapp": "+79671234508"},
        "tags": ["математика", "английский B2", "дети 7-14 лет", "онлайн/офлайн"],
        "notes": "Выпускница мехмата МГУ. Результативно готовит к олимпиадам.",
    },
    # --- Водители ---
    {
        "full_name": "Кузнецов Дмитрий Александрович",
        "age": 47,
        "specialization": "личный водитель",
        "experience_years": 20,
        "salary_min": 80000,
        "salary_max": 110000,
        "availability": "сразу",
        "contacts": {"telegram": "@dmitry_driver", "whatsapp": "+79251234509"},
        "tags": ["VIP-перевозки", "категории B C", "охранное удостоверение", "без вредных привычек"],
        "notes": "Опыт работы с высокопоставленными клиентами. Знает Москву и МО.",
    },
    {
        "full_name": "Орлов Максим Викторович",
        "age": 34,
        "specialization": "личный водитель",
        "experience_years": 8,
        "salary_min": 65000,
        "salary_max": 85000,
        "availability": "с 5 мая 2026",
        "contacts": {"whatsapp": "+79111234510"},
        "tags": ["категории B C D", "дальние поездки", "аэропорт", "встреча гостей"],
        "notes": "Некурящий. Опыт дальних поездок по России и Европе.",
    },
    # --- Экономки ---
    {
        "full_name": "Громова Людмила Фёдоровна",
        "age": 50,
        "specialization": "экономка / управляющая домом",
        "experience_years": 22,
        "salary_min": 110000,
        "salary_max": 160000,
        "availability": "с 1 июня 2026",
        "contacts": {"telegram": "@luda_economy", "email": "gromova.luda@mail.ru"},
        "tags": ["управление персоналом", "закупки", "контроль бюджета", "ивент-планирование"],
        "notes": "Управляла загородными поместьями до 15 человек персонала.",
    },
    {
        "full_name": "Степанова Наталья Борисовна",
        "age": 43,
        "specialization": "экономка",
        "experience_years": 12,
        "salary_min": 85000,
        "salary_max": 115000,
        "availability": "сразу",
        "contacts": {"whatsapp": "+79041234511", "email": "stepanova.nb@yandex.ru"},
        "tags": ["ведение хозяйства", "персонал", "закупки", "ремонт и сервис"],
        "notes": "Организованная, стрессоустойчивая. Умеет вести учёт расходов.",
    },
    # --- Садовники ---
    {
        "full_name": "Семёнов Виктор Павлович",
        "age": 55,
        "specialization": "садовник / ландшафтный дизайнер",
        "experience_years": 25,
        "salary_min": 60000,
        "salary_max": 90000,
        "availability": "сразу",
        "contacts": {"whatsapp": "+79191234512"},
        "tags": ["ландшафтный дизайн", "огород", "обрезка деревьев", "газон", "полив"],
        "notes": "Специализируется на японских и английских садах. Есть своя бригада.",
    },
    {
        "full_name": "Жуков Артём Игоревич",
        "age": 30,
        "specialization": "садовник",
        "experience_years": 6,
        "salary_min": 45000,
        "salary_max": 65000,
        "availability": "сезонно, с апреля",
        "contacts": {"telegram": "@artem_garden"},
        "tags": ["обрезка", "посадка", "теплицы", "автополив"],
        "notes": "Агрономическое образование. Работает в Подмосковье и МО.",
    },
    # --- Личные помощники ---
    {
        "full_name": "Крылова Анастасия Сергеевна",
        "age": 26,
        "specialization": "личный помощник / ассистент",
        "experience_years": 3,
        "salary_min": 70000,
        "salary_max": 95000,
        "availability": "сразу",
        "contacts": {"telegram": "@nastya_pa", "email": "krylova.a@gmail.com"},
        "tags": ["планирование", "travel-организация", "английский C1", "документооборот"],
        "notes": "Опыт работы с известными предпринимателями. Абсолютная конфиденциальность.",
    },
    {
        "full_name": "Борисова Дарья Олеговна",
        "age": 31,
        "specialization": "личный помощник",
        "experience_years": 6,
        "salary_min": 85000,
        "salary_max": 120000,
        "availability": "с 1 мая 2026",
        "contacts": {"telegram": "@dasha_asst", "whatsapp": "+79281234513"},
        "tags": ["английский C2", "французский B1", "ненормированный день", "VIP-клиенты"],
        "notes": "Работала помощником у топ-менеджеров банка. Готова к командировкам.",
    },
    # --- Сиделки ---
    {
        "full_name": "Панова Зинаида Ивановна",
        "age": 48,
        "specialization": "сиделка / медицинская сестра",
        "experience_years": 16,
        "salary_min": 65000,
        "salary_max": 85000,
        "availability": "сразу",
        "contacts": {"whatsapp": "+79051234514"},
        "tags": ["пожилые", "постоперационный уход", "медсестра", "проживание", "суточный режим"],
        "notes": "Медицинское образование, опыт в геронтологии. Терпелива, отзывчива.",
    },
    {
        "full_name": "Трофимова Валентина Сергеевна",
        "age": 54,
        "specialization": "сиделка",
        "experience_years": 20,
        "salary_min": 55000,
        "salary_max": 75000,
        "availability": "сразу",
        "contacts": {"telegram": "@valentina_care", "whatsapp": "+79131234515"},
        "tags": ["пожилые", "деменция", "реабилитация", "инвалидность"],
        "notes": "Специализируется на уходе при деменции и после инсульта.",
    },
    # --- Повара / кейтеринг ---
    {
        "full_name": "Макаров Илья Константинович",
        "age": 37,
        "specialization": "шеф-повар / кейтеринг",
        "experience_years": 13,
        "salary_min": 120000,
        "salary_max": 180000,
        "availability": "с 20 мая 2026",
        "contacts": {"telegram": "@chef_makarov", "email": "makarov.chef@gmail.com"},
        "tags": ["haute cuisine", "молекулярная кухня", "ужины под ключ", "банкеты до 200 чел."],
        "notes": "Работал в 2 ресторанах Michelin. Готов к разовым мероприятиям и постоянной работе.",
    },
    # --- Репетиторы ---
    {
        "full_name": "Алексеева Ксения Игоревна",
        "age": 24,
        "specialization": "репетитор / гувернантка",
        "experience_years": 2,
        "salary_min": 50000,
        "salary_max": 70000,
        "availability": "сразу",
        "contacts": {"telegram": "@ksenya_tutor"},
        "tags": ["английский B2", "математика", "начальная школа", "дошкольники"],
        "notes": "Студентка педагогической магистратуры. Живая, творческая, любит детей.",
    },
    # --- Помощники по хозяйству ---
    {
        "full_name": "Дмитриева Светлана Александровна",
        "age": 40,
        "specialization": "помощница по хозяйству",
        "experience_years": 10,
        "salary_min": 45000,
        "salary_max": 60000,
        "availability": "сразу",
        "contacts": {"whatsapp": "+79171234516"},
        "tags": ["уборка", "стирка", "готовка", "закупки"],
        "notes": "Универсальная помощница. Ответственная, без вредных привычек.",
    },
    {
        "full_name": "Егорова Тамара Петровна",
        "age": 46,
        "specialization": "помощница по хозяйству / нянечка",
        "experience_years": 15,
        "salary_min": 50000,
        "salary_max": 68000,
        "availability": "с 1 мая 2026",
        "contacts": {"whatsapp": "+79061234517", "telegram": "@tamara_house"},
        "tags": ["уборка", "дети", "приготовление еды", "проживание возможно"],
        "notes": "Совмещает обязанности помощницы и нянечки. Опыт в 5 семьях.",
    },
    # --- Охранники / личная охрана ---
    {
        "full_name": "Соколов Роман Евгеньевич",
        "age": 42,
        "specialization": "личный охранник / телохранитель",
        "experience_years": 18,
        "salary_min": 120000,
        "salary_max": 200000,
        "availability": "с 5 мая 2026",
        "contacts": {"telegram": "@roman_security", "whatsapp": "+79231234518"},
        "tags": ["лицензия охранника", "силовые структуры", "вождение", "иностранные языки"],
        "notes": "Бывший военный. Лицензия ЧОП. Готов к суточному режиму.",
    },
    # --- Специальные профили ---
    {
        "full_name": "Яковлева Людмила Петровна",
        "age": 49,
        "specialization": "гувернантка / домашний учитель",
        "experience_years": 19,
        "salary_min": 95000,
        "salary_max": 135000,
        "availability": "с 1 июня 2026",
        "contacts": {"email": "yakovleva.lp@mail.ru", "whatsapp": "+79141234519"},
        "tags": ["английский C2", "немецкий C1", "фортепиано", "дети 6-18 лет", "IB программа"],
        "notes": "20 лет опыта в семьях дипломатов. Готова к переезду за рубеж.",
    },
    {
        "full_name": "Никитин Сергей Владимирович",
        "age": 38,
        "specialization": "мажордом",
        "experience_years": 11,
        "salary_min": 130000,
        "salary_max": 200000,
        "availability": "сразу",
        "contacts": {"telegram": "@sergey_butler", "email": "nikitin.butler@gmail.com"},
        "tags": ["управление домом", "персонал", "протокол", "английский C1", "VIP"],
        "notes": "Прошёл обучение в Butler Academy London. Опыт в частных резиденциях ОАЭ.",
    },
    {
        "full_name": "Власова Марина Юрьевна",
        "age": 36,
        "specialization": "travel-нянечка / au pair",
        "experience_years": 8,
        "salary_min": 80000,
        "salary_max": 120000,
        "availability": "сразу",
        "contacts": {"telegram": "@marina_aupair", "whatsapp": "+79241234520"},
        "tags": ["дети до 10 лет", "выезд за рубеж", "английский C1", "языковая среда", "путешествия"],
        "notes": "Специализируется на работе с семьями, которые часто путешествуют. Загранпаспорт.",
    },
]


async def seed():
    engine = create_async_engine(DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        async with session.begin():
            for data in CANDIDATES:
                obj = Candidate(**data)
                session.add(obj)

    print(f"✅ Добавлено {len(CANDIDATES)} соискателей в базу данных.")
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
